name: gtest_demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS_DEBUG="/MDd" -DCMAKE_CXX_FLAGS_DEBUG="/MDd" -DCMAKE_C_FLAGS_RELEASE="/MD" -DCMAKE_CXX_FLAGS_RELEASE="/MD"

    - name: Build project
      run: cmake --build build --config Debug

    - name: Run tests
      run: cd build && ctest --output-on-failure -C Debug -j 8

    - name: Generate Test Report
      run: |
          cd build
          ctest -T test --no-compress-output -C Debug -j 8

    - name: Upload Results
      uses: actions/upload-artifact@v4
      with:
          name: gtest-results
          path: build/Testing

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install requests
          
    - name: Feishu Notify
      if: always()
      #run: bash send_feishu.sh
      run: python send_feishu.py
